### ISSUE TITLE
bug when Config_ItemAmount[x] is nil

### ISSUE THREAD

**Issue by vitsumoc** [55Honey/Acore_LevelUpReward#5]
https://github.com/55Honey/Acore_LevelUpReward/blob/4e0d3ec8329ea93534df49041e16b965abff694c/LevelUpReward.lua#L182
last param shold be "itemAmount " but not the "Config_ItemAmount[oldLevel + 1]"

![image](https://github.com/55Honey/Acore_LevelUpReward/assets/31403302/af56c73b-4765-4595-a5e1-f438127ce85f)

**Comment by 55Honey** [comment]
Thanks for the report!
